config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'ordens' => 'ordenes#new'
  post 'ordens' => 'ordenes#new'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'cotiza' => 'estaticas#cotiza'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  get 'trazaruta' => 'estaticas#rutas'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  match '/cotizacion', to: 'pides#new', via: 'get'
  resources "cotizacion", only: [:new, :create]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_usuario,   only: [:edit, :update]
	before_action :valid_usuario, only: [:edit, :update]
	before_action :check_expiration, only: [:edit, :update]
  def new
  end

  def create
    @usuario = Usuario.find_by(email: params[:password_reset][:email].downcase)
    if @usuario
      @usuario.create_reset_digest
      @usuario.send_password_reset_email
      flash[:info] = "Te mandamos un mail con instrucciones secretas para que obtengas un nuevo password."
      redirect_to root_url
    else
      flash.now[:danger] = "No existe ese mail en nuestra base!"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:usuario][:password].empty?
      flash.now[:danger] = "El password no puede estar en blanco"
      render 'edit'
    elsif @usuario.update_attributes(usuario_params)
      log_in @usuario
      flash[:success] = "¡Felicidades! Tienes nuevo password :)"
      redirect_to @usuario
    else
      render 'edit'
    end
  end

  private

  def usuario_params
      params.require(:usuario).permit(:password, :password_confirmation)
    end

  def get_usuario
      @usuario = Usuario.find_by(email: params[:email])
  end

  # Confirms a valid user.
	def valid_usuario
	  unless (@usuario && @usuario.activated? &&
	          @usuario.authenticated?(:reset, params[:id]))
	    
	  end
	end

	# Checks expiration of reset token.
    def check_expiration
      if @usuario.password_reset_expired?
        flash[:danger] = "Ya expiró el link :("
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Nuevo password | ") %>
<h1>Crea un nuevo password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @usuario.email %>

      <%= f.label :password, "Nuevo password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmación" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear nuevo password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Recupera password | ") %>
<h1>Recupera tu password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Enviar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>