config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'ordens' => 'ordenes#new'
  post 'ordens' => 'ordenes#new'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'cotiza' => 'estaticas#cotiza'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  get 'trazaruta' => 'estaticas#rutas'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  match '/cotizacion', to: 'pides#new', via: 'get'
  resources "cotizacion", only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer id="footer-1 bg-dark">

          <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                          <%= image_tag 'logo-bicimensajero-light.png', alt: 'Logo', :class => 'logo' %>
                        </div>
                        
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6">
                            <span class="sub">&copy; Copyright 2015 - Bicimensajero</span>
                            <li><h4><%= link_to "Acerca de nosotros", acercade_path %></h4></li>
                            <li><h4><%= link_to "Contacto", contacto_path %></h4></li>
                            <li><h4><%= link_to "Aviso de privacidad", privacidad_path %></h4></li>
                            <li>Ignacio Allende #21 Colonia Ampliación Torreblanca, 11289, México DF</li>
                        </div>
                        <div class="col-sm-6 text-right">
                            <ul class="list-inline social-list">
                                <li>
                                    <a href="https://twitter.com/BicimensajeroMX" target="_blank">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/MensajerosMX" target="_blank">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>                               
                                <li>
                                    <a href="elements-tabs.html#">
                                        <i class="ti-vimeo-alt"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
          <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3AVY2thZrxj2xtZbwcSnJdliHJZkIfty";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('.alert-warning').slideUp();
  }, 7000);
 })
</script>

</footer>

app/views/layouts/_header.html.erb
		<div class="nav-container">
            <a id="top"></a>
            <nav>
            	
                <div class="nav-utility">
                    <div class="module left">
                        <i class="ti-location-arrow">&nbsp;</i>
                        <span class="sub">Whastapp 55 31 12 04 98</span>
                    </div>
                    <div class="module left">
                        <i class="ti-email">&nbsp;</i>
                        <span class="sub">amo@bicimensajero.com</span>
                    </div>

                    <div class="module right">

                        <a class="btn btn-sm btn-rounded" href="#">Cotiza un envío</a>
                        
                    </div>
                </div>

                <div class="nav-bar">
                    <div class="module left">
                        <%= link_to root_path do %>
                        	<%= image_tag 'logo-bicimensajero-light.png', width: 200, alt: 'Bicimensajero' %>
                        <% end %>
                    </div>
                    <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                        <i class="ti-menu"></i>
                    </div>
                    <div class="module-group right">
                        <div class="module left">
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        Inicio
                                    </a>    
                                </li>
                                <li>
                                    <a href="#">
                                        Únete
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Blog
                                    </a>
                                    
                                </li>
                               
                            </ul>
                        </div>
                        <!--end of menu module-->
                        <div class="module widget-handle cart-widget-handle left">
                            <div class="cart">
                                <i class="ti-user"></i>
                                <span class="title">Login</span>
                            </div>
                            <div class="function">
                                <div class="widget">                                 
                                    <hr>

                                    <% if logged_in? && current_usuario.admin? %>
                                    <%= link_to "Usuarios", usuarios_path, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Perfil", current_usuario, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Ajustes de mi cuenta", edit_usuario_path(current_usuario), :class => 'btn btn-sm btn-filled' %>
									<%= link_to "Cerrar sesión", logout_path, method: "delete", :class => 'btn btn-sm btn-filled' %>

									<% elsif logged_in? %>

									<%= link_to "Perfil", current_usuario, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Ajustes de mi cuenta", edit_usuario_path(current_usuario), :class => 'btn btn-sm btn-filled' %>
									<%= link_to "Cerrar sesión", logout_path, method: "delete", :class => 'btn btn-sm btn-filled' %>

									<% else %>

									<%= link_to "Crea una cuenta", nuevacuenta_path, :class => 'btn btn-sm' %>
									<%= link_to "Ingresa a tu cuenta", login_path, :class => 'btn btn-sm btn-filled' %>	

									<% end %>

                                </div>
                                <!--end of widget-->
                            </div>
                        </div>
                        <!-- Idioma -->
                        <!--
                        <div class="module widget-handle language left">
                            <ul class="menu">
                                <li class="has-dropdown">
                                    <a href="elements-tabs.html#">ENG</a>
                                    <ul>
                                        <li>
                                            <a href="elements-tabs.html#">French</a>
                                        </li>
                                        <li>
                                            <a href="elements-tabs.html#">Deutsch</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        -->
                    </div>
                    <!--end of module group-->
                </div>
            </nav>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=0.8">
  <title><%= yield(:title) %>Bicimensajero | Servicio de logística urbana y sustentable.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body data-no-turbolink="true">

        <div class="nav-container">
          <%= render 'layouts/header' %>
        </div>
      


    <!--Mostrar Terminal-->
    <div class="">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>

</body>
</html>